### ISSUE TITLE
Merge with Upstream Maui.Essentials

### ISSUE THREAD

**Issue by robloo** [AvaloniaUI/Avalonia.Essentials#2]
I heard mentioned on the community Q&A that it was basically a non-starter to share effort with the Maui team simply due to the project naming "Maui.Essentials". This is an example of a decision that I think isn't well thought out and something Avalonia in the past would not have done.

Simply put, I'm very surprised by that statement and consider it a poor strategic decision. It also leaves the taste of a decision made without the best interests of the community in mind or a "play fair" mindset. Let me explain:

 1. The obvious elephant in the room is you are standing on their shoulders here. That project did ALL the heavy lifting to get essentials to what it is today. It doesn't make sense to try and discard that for your own marketing purposes -- you didn't earn it. Open source and even commercial projects need to play nicer together than that. Don't burn good will right off the bat if there is another way.
 1. Combining efforts with upstream Maui.Essentials will reduce a lot of overhead maintaining this repo. It makes sense simply from a manpower and cost statement.
 2. Previously it was stated that Microsoft was not interested in combining efforts. Now they seemed to have opened up to the idea yet the door is being closed by Avalonia. That at first glance is a 180-degree turn from earlier messaging. It's a much better public look to not be the one saying no here and find the compromises.
 3. These are all open-source projects. Fairness and compromise need to be maximized. Pride and corporate interests minimized. That's for the good of everyone -- the companies included.
 4. Xamarin.Essentials, now Maui.Essentials did nothing wrong with naming in the beginning. The project itself seemed perfectly logical to include at the time. It very likely wasn't decided from a commercial close-the-door-for-everyone-else type of thinking.
 5. I recommend watching what the Uno Platform does in situations like this. They have a lot more experience in some areas. They also readily recommend Maui.Essentials and the naming issue hasn't ever publicly come up.

The ONLY reason I see not to merge with upstream is if they don't allow Browser and Linux code. That's the only real showstopper that would require maintaining a fork.

I think any well thought-out business case would come to similar conclusions.

**Comment by maxkatz6** [comment]
I can only speak on technical problems we would have here.
Avalonia supports Windows, macOS and linux without any special TFM requirements. I.e. you can just create "net6.0" project, add avalonia into it and run. 
And from used APIs, Avalonia is using full macOS API set and Win32 classic API (in some cases using WinRT when it's only ghe option). 

Now, with MAUI.Essentials it would be drastically different, making this package incompatible with the most of avalonia apps. 
It requires specific target framework used for all platforms that are supported by SDK (i.e. no browser or linux). On windows it uses exclusively latest WinRT APIs forcing apps to target something like 1809 windows or newer. And on macOS it uses Mac Catalyst API set, which isn't dupported by Avalonia (since we support full macOS, we never had any demand for Catalyst). 

To be clear, these limitations don't come from MAUI team, but from whoever decided to invest target frameworks and API wrappers available only when you have a correct target framework. Up to this day I don't understand why we need to use this approach when we had runtime identifiers, runtime checks and trimmer working per target runtime. 

And if MAUI team is open to make these improvements and made Essentials library usable even with plain "net6.0" target, it's going to be a huge task. 

Imho, way more realistic approach would be to add "net8.0-browser" implementations, and assume that "net8.0" target without any platform is always a linux target (or runtime exception, if it's not). Not ideal and not quite useful with Avalonia apps (unless we force them to migrate to multiple target frameworks projects), but at least it's morr realistic.

**Comment by maxkatz6** [comment]
To add, my previous comment mostly touches desktop implementations. With mobile it is easier, as Avalonia mobile applications target the same TFMs as Maui, making it compatible. 
I.e. just add this package (requires net8.0 target) https://www.nuget.org/packages/Microsoft.Maui.Essentials/8.0.0-preview.6.8686 and it works. At least on mobile.

**Comment by MikeCodesDotNET** [comment]
Thank you for your candid feedback. Different perspectives help us grow, and your insights are valuable to us. I understand that not all decisions will meet everyone's expectations, and I'm genuinely interested in hearing your thoughts.

How about a chat where we can address any misunderstandings and explore possible improvements? If you're open to it, let's set a time that works for you. Feel free to reach out directly to arrange this.

Looking forward to our conversation!

**Comment by robloo** [comment]
@maxkatz6 Thanks for the technical details, you've definitely looked at this aspect more than I have. My guess is upstream would be open to discussing this specifically since in some ways it affects Maui as well (at least the community Linux support). I could be wrong though. If there are in the end clear technical roadblocks I totally understand that.

@MikeCodesDotNET I'm happy to have a chat at your convenience. Will send an email shortly to arrange timing.

**Comment by robloo** [comment]
Per discussion (thanks @MikeCodesDotNET) this is largely a misunderstanding:

 * Branding is not a showstopper (my main concern above)
 * Goal is NOT to fragment the ecosystem
 * The technical concerns for browser and Linux support are so far unsolved (per @maxkatz6 comments)
 * Discussion is ongoing where possible
